### ISSUE TITLE
More advanced input and output matching

### ISSUE THREAD

**Issue by gaow** [bpeng2000/SOS#53]
I have this SoS step that uses output from two previous steps and my 

```
def get_input(values):
    return sum(list(zip(*itertools.product(*values))), ())

[mse_1: alias = 'mse']
output_suffix = 'rds'
input_files = get_input((simulate.output, estimate.output))
input: input_files, group_by = 'pairs', pattern = '{base}.{ext}'
output: get_md5(expand_pattern('exec=MSE.R.{_base}.${output_suffix}'))
process: workdir = './'
...
```
What I want to achieve here is to take every paired combination of output from a step with alias `simulate` and another step with alias `estimate`, get output names for these pairs (one pair will have one unique output), and feed them to an action. The action is something like this:

```
def foo(value1, value2):
  return value3
```
So two input values (a pair) will result in one output, and the output file name can be composed of both of these input file names. 

My codes above does not give me what I want. In fact it seems SoS simply does not run this step. The complete script is here:

[1.sos.txt](https://github.com/bpeng2000/SOS/files/190999/1.sos.txt)

**Comment by bpeng2000** [comment]
For some reason `__builtints__` is not copied to SoS namespace as promised by python documentation. Might be another Python 3 difference.

**Comment by bpeng2000** [comment]
Wow, this is a weird that took me hours to hunt down. Basically, the `exec` function of Python, for performance considerations, does not treat a derived class of `dict` as a derived class so `__builtins__` could not be found after it is assigned to the `dict`. I had to rewrite the workflow dict to send `exec` a real dictionary to fix this problem. It should now works.

**Comment by gaow** [comment]
That's weird ... I derive `dict` quite often myself. Good to know this. 

My example still does not work and it seems nothing is changed, i.e., the last step is still skipped. Perhaps my installation is messed up? Just wondering if it worked on your end ...

**Comment by bpeng2000** [comment]
I tried sos dryrun 1.sos DSC

**Comment by gaow** [comment]
Yes, and the last line of output below still says "step 1 is skipped". I tried uninstall / install but the problem sticks. If you get a different output then I must be missing something weird ... 

```
[GW] sos dryrun 1.sos DSC
INFO: Execute DSC_1: 
INFO: _step.input:   []
INFO: _step.output:  []
INFO: _idx: 0
INFO: _input: []
INFO: _output: []
INFO: Execute simulate_1: 
INFO: _step.input:   []
INFO: _step.output:  ['7b6a5af72eaaf6a9d5ad0d4ca21eb349.rds', '8e595e2a1634ae5d0b0a2dff6a0bba88.rds']
INFO: _idx: 0
INFO: _input: []
INFO: _output: ['7b6a5af72eaaf6a9d5ad0d4ca21eb349.rds']
INFO: _idx: 1
INFO: _input: []
INFO: _output: ['8e595e2a1634ae5d0b0a2dff6a0bba88.rds']
INFO: Execute estimate_1: 
INFO: _step.input:   ['7b6a5af72eaaf6a9d5ad0d4ca21eb349.rds', '8e595e2a1634ae5d0b0a2dff6a0bba88.rds']
INFO: _step.output:  ['b2eba77d1a492d0ec3aac735064b45c3.rds', '352d5e05ef793b7eac5d58f18baa2aad.rds']
INFO: _idx: 0
INFO: _input: ['7b6a5af72eaaf6a9d5ad0d4ca21eb349.rds']
INFO: _output: ['b2eba77d1a492d0ec3aac735064b45c3.rds']
INFO: _idx: 1
INFO: _input: ['8e595e2a1634ae5d0b0a2dff6a0bba88.rds']
INFO: _output: ['352d5e05ef793b7eac5d58f18baa2aad.rds']
INFO: Execute mse_1: 
INFO: Step 1 is skipped
```

**Comment by bpeng2000** [comment]
Oh, the problem was that your function returns tuple, not list. I have changed to allow arbitrary sequence in other places but not in the handling of `input` keyword. Please try again.

**Comment by gaow** [comment]
Hmm ... I updated but still having the same `Step 1 is skipped` problem ... after changing my function to return to list it works! I guess this is what you meant: for `input`, only list is allowed? 

Also it comes to the 2nd part of the question: how can I properly line-up output file name when there are multiple input files coming in batches but one output file? For example in this case:

```
input: input_files, group_by = 'pairs', pattern = '{base}.{ext}'
output: get_md5(expand_pattern('exec=MSE.R.{_base}.${output_suffix}'))
```
Each input is a pair of files. For example, (1.txt, 2,txt), (3.txt, 4.txt). I was hoping for something that can extract patterns of `1_2`, `3_4` for use with output; or other welcomed solutions that can reflect what are the input files in output names. Currently the `_base` variable apparently does not do the job right.

**Comment by bpeng2000** [comment]
It should accept `tuple` etc once you update, and I am allowing Iterable such as `set` now, with proper testing.

`_base` should be the way to go and I do not know why it does not work. Anyway, you can always add `print` statement in the middle and check the values of `_input`, `_base` and `base`.

**Comment by bpeng2000** [comment]
```
def get_md5(values):
    res = []
    for value in values:
        base, ext = value.rsplit('.', 1)
    res.append('{}.{}'.format(hashlib.md5(base.encode('utf-8')).hexdigest() if sys.version_info[0] == 3 else hashlib.md5(base).hexdigest(), ext))
    return res
```

It appears that your `get_md5

**Comment by gaow** [comment]
Well, I did update but without converting output of my function to `list` the issue remains.

I'm trying to play with `base` and the following is supposed to work (where I manually mimic the behavior of `pairs` in `base` by re-assigning base which should probably be discouraged), but it does not -- the output still seem to use the `_base` before I reassign its value. 

```
input: input_files, group_by = 'pairs', pattern = '{base}.{ext}'
base = ['{}_{}'.format(x,y) for x, y in zip(base[:int(len(base)/2)], base[int(len(base)/2):])]
print(base)
output: get_md5(expand_pattern('exec=MSE.R.{_base}.${output_suffix}'))
print(_output)
```

Your comment above is in-complete ... what is the issue there?

**Comment by bpeng2000** [comment]
What is the out put of print _base?

**Comment by bpeng2000** [comment]
When I add print statements like

```
input: input_files, group_by = 'pairs', pattern = '{base}.{ext}'
print('base=${base!,}')
print('_base=${_base!,}')
output: get_md5(expand_pattern('exec=MSE.R.{_base}.${output_suffix}'))
print('_output=${_output!,}')
```

I get

```
base=7b6a5af72eaaf6a9d5ad0d4ca21eb349,7b6a5af72eaaf6a9d5ad0d4ca21eb349,8e595e2a1634ae5d0b0a2dff6a0bba88,8e595e2a1634ae5d0b0a2dff6a0bba88,b2eba77d1a492d0ec3aac735064b45c3,352d5e05ef793b7eac5d58f18baa2aad,b2eba77d1a492d0ec3aac735064b45c3,352d5e05ef793b7eac5d58f18baa2aad, _base=7b6a5af72eaaf6a9d5ad0d4ca21eb349,b2eba77d1a492d0ec3aac735064b45c3
_output=d78923709fe29b1eb8b4a3345e6477fc.rds
base=7b6a5af72eaaf6a9d5ad0d4ca21eb349,7b6a5af72eaaf6a9d5ad0d4ca21eb349,8e595e2a1634ae5d0b0a2dff6a0bba88,8e595e2a1634ae5d0b0a2dff6a0bba88,b2eba77d1a492d0ec3aac735064b45c3,352d5e05ef793b7eac5d58f18baa2aad,b2eba77d1a492d0ec3aac735064b45c3,352d5e05ef793b7eac5d58f18baa2aad, _base=7b6a5af72eaaf6a9d5ad0d4ca21eb349,352d5e05ef793b7eac5d58f18baa2aad
_output=05ef46ef5e261245f194b866d9afbf33.rds
base=7b6a5af72eaaf6a9d5ad0d4ca21eb349,7b6a5af72eaaf6a9d5ad0d4ca21eb349,8e595e2a1634ae5d0b0a2dff6a0bba88,8e595e2a1634ae5d0b0a2dff6a0bba88,b2eba77d1a492d0ec3aac735064b45c3,352d5e05ef793b7eac5d58f18baa2aad,b2eba77d1a492d0ec3aac735064b45c3,352d5e05ef793b7eac5d58f18baa2aad, _base=8e595e2a1634ae5d0b0a2dff6a0bba88,b2eba77d1a492d0ec3aac735064b45c3
_output=d78923709fe29b1eb8b4a3345e6477fc.rds
base=7b6a5af72eaaf6a9d5ad0d4ca21eb349,7b6a5af72eaaf6a9d5ad0d4ca21eb349,8e595e2a1634ae5d0b0a2dff6a0bba88,8e595e2a1634ae5d0b0a2dff6a0bba88,b2eba77d1a492d0ec3aac735064b45c3,352d5e05ef793b7eac5d58f18baa2aad,b2eba77d1a492d0ec3aac735064b45c3,352d5e05ef793b7eac5d58f18baa2aad, _base=8e595e2a1634ae5d0b0a2dff6a0bba88,352d5e05ef793b7eac5d58f18baa2aad
_output=05ef46ef5e261245f194b866d9afbf33.rds
```

which makes sense to me.

**Comment by gaow** [comment]
`base` before the massage is (corresponding to the input):

```
['7b6a', '7b6a', '8e59', '8e59', 'b2eb', '352d', 'b2eb', '352d']
```

and after, is:
```
['7b6a_b2eb', '7b6a_352d', '8e59_b2eb', '8e59_352d']
```
So the `output` should be 4 different file names due to difference in `_base`. However output is:

```
['d78923709fe29b1eb8b4a3345e6477fc.rds']
['05ef46ef5e261245f194b866d9afbf33.rds']
['d78923709fe29b1eb8b4a3345e6477fc.rds']
['05ef46ef5e261245f194b866d9afbf33.rds']
```
which duplicates.

**Comment by gaow** [comment]
The point of massaging base is to make sure that the input 8 files will generate 4 output files. Behavior of `base` corresponds to the input but I need to transform it to work with the output. But it seems `output`  did not honor my massage. Should I do it differently? I do feel cheat on `base` directly is kind of ugly. The complete version of my current last step is:

```
[mse_1: alias = 'mse']
output_suffix = 'rds'
input_files = get_input((simulate.output, estimate.output))
input: input_files, group_by = 'pairs', pattern = '{base}.{ext}'
base = ['{}_{}'.format(x,y) for x, y in zip(base[:int(len(base)/2)], base[int(len(base)/2):])]
#print(base)
output: get_md5(expand_pattern('exec=MSE.R.{_base}.${output_suffix}'))
#print(_output)
process: workdir = './'
run('''
echo R/scores/MSE.R
echo Input:
echo ${_input}
echo Parameters:

echo Output:
echo "	output: ${_output!r}"
touch ${_output}
''')
```

**Comment by bpeng2000** [comment]
Look at this piece of code

```
def get_md5(values):
    res = []
    for value in values:
        base, ext = value.rsplit('.', 1)
    res.append('{}.{}'.format(hashlib.md5(base.encode('
```

you are only using the second file to generate md5.

**Comment by gaow** [comment]
Oops bad indentation! That was rather dumb ... after fixing that and removing my massage to `base` I end up having 8 input and 4 output:

```
INFO: _step.input:   ['7b6a5af72eaaf6a9d5ad0d4ca21eb349.rds', ...] (8 items)
INFO: _step.output:  ['60d48f0501ce624f3c3d98a002613636.rds', ...] (4 items)
```

However, the outcome is still not right. I was hoping each pair of input correspond to one output, but what happened was this:

```
R/scores/MSE.R
Input:
7b6a5af72eaaf6a9d5ad0d4ca21eb349.rds b2eba77d1a492d0ec3aac735064b45c3.rds
Parameters:
Output:
	output: '60d48f0501ce624f3c3d98a002613636.rds' 'd78923709fe29b1eb8b4a3345e6477fc.rds'
R/scores/MSE.R
Input:
7b6a5af72eaaf6a9d5ad0d4ca21eb349.rds 352d5e05ef793b7eac5d58f18baa2aad.rds
Parameters:
Output:
	output: '60d48f0501ce624f3c3d98a002613636.rds' '05ef46ef5e261245f194b866d9afbf33.rds'
R/scores/MSE.R
Input:
8e595e2a1634ae5d0b0a2dff6a0bba88.rds b2eba77d1a492d0ec3aac735064b45c3.rds
Parameters:
Output:
	output: '9df18b5e3ddb5d5141206812690a9412.rds' 'd78923709fe29b1eb8b4a3345e6477fc.rds'
R/scores/MSE.R
Input:
8e595e2a1634ae5d0b0a2dff6a0bba88.rds 352d5e05ef793b7eac5d58f18baa2aad.rds
Parameters:
Output:
	output: '9df18b5e3ddb5d5141206812690a9412.rds' '05ef46ef5e261245f194b866d9afbf33.rds'
```
You see although there are 4 items for `_step.output` it was somehow processed to match with the number of input. I can use slice to make it work here, but the behavior is counter-intuitive. Is this expected?

**Comment by bpeng2000** [comment]
I am not sure what exactly you want to achieve. Here you have overlapping `_output` because of overlapping `_input`. `_step.output` is the sum of all `_output` while removing all duplicate items and keeping original order.

**Comment by bpeng2000** [comment]
If you are supposed to get an unique `_output` file for each pair of `_input`, you need to change `get_md5` to produce a single md5 from both `_input` files. You previously use only the second file, and now you are producing two `_output` files.

**Comment by gaow** [comment]
Right ... that was why I wanted to massage `_base` first (`base = ['{}_{}'.format(x,y) for x, y in zip(base[:int(len(base)/2)], base[int(len(base)/2):])]`) before I feed it. But it seems this did not have an impact, possibly again because of namespace.

I'll try to find a way to consolidate the names for the md5 calculation. Thanks a lot!
